baseURL = "https://example.com"
languageCode = "en"
title = "Monochrome"
defaultContentLanguage = "en"
enableEmoji = true
enableGitInfo = true

[pagination]
pagerSize = 5

[paginationOptions]
neighborPages = 2

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]

[modules]
    [[module.imports]]
       # path = "github.com/VinayIN/hugo-theme-monochrome"
