baseURL = "https://example.com"
locale = "en"
title = "Monochrome"
defaultContentLanguage = "en"
enableEmoji = true
enableGitInfo = true

[pagination]
pagerSize = 5

[paginationOptions]
neighborPages = 2

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]

[module]
    [[module.imports]]
       path = "github.com/VinayIN/hugo-theme-monochrome"

    # Use the parent directory as the module source during local development
    replacements = [
        "github.com/VinayIN/hugo-theme-monochrome => .."
    ]
