navbar_title = 'Monochrome'
footer = "Copyright © 2021-2025 by Vinay"
author = "Vinay"
color_scheme = "light"

enable_zooming_js = true
enable_header_anchor = true
enable_toc = true
enable_site_search = true
enable_math = false

# SEO
enable_open_graph = true
enable_twitter_cards = true

# Collapsible Menu
enable_collapsible_toc = false
enable_collapsible_changelogs = true

[list_layout]
enable_group_by_year = true
enable_show_date = true
enable_pagination = true

# syntax highlight settings
[syntax_highlight]
lib = "prism.js" # "builtin" | "prism.js"

    [syntax_highlight.builtin]
    enable_code_copy = true

    [syntax_highlight.prism]
    enable_code_copy = true
    enable_line_no = false
